onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /system_tb/CLK
add wave -noupdate /system_tb/nRST
add wave -noupdate /system_tb/DUT/CPU/DP/SignExt
add wave -noupdate /system_tb/DUT/CPU/DP/ZeroExt
add wave -noupdate /system_tb/DUT/CPU/DP/LuiExt
add wave -noupdate /system_tb/DUT/CPU/DP/Jump
add wave -noupdate /system_tb/DUT/CPU/DP/Branch
add wave -noupdate /system_tb/DUT/CPU/DP/JumpR
add wave -noupdate /system_tb/DUT/CPU/CM/instr
add wave -noupdate /system_tb/DUT/CPU/CM/daddr
add wave -noupdate /system_tb/DUT/CPU/ccif/CPUS
add wave -noupdate /system_tb/DUT/CPU/ccif/iwait
add wave -noupdate /system_tb/DUT/CPU/ccif/dwait
add wave -noupdate /system_tb/DUT/CPU/ccif/iREN
add wave -noupdate /system_tb/DUT/CPU/ccif/dREN
add wave -noupdate /system_tb/DUT/CPU/ccif/dWEN
add wave -noupdate /system_tb/DUT/CPU/ccif/iload
add wave -noupdate /system_tb/DUT/CPU/ccif/dload
add wave -noupdate /system_tb/DUT/CPU/ccif/dstore
add wave -noupdate /system_tb/DUT/CPU/ccif/iaddr
add wave -noupdate /system_tb/DUT/CPU/ccif/daddr
add wave -noupdate /system_tb/DUT/CPU/ccif/ccwait
add wave -noupdate /system_tb/DUT/CPU/ccif/ccinv
add wave -noupdate /system_tb/DUT/CPU/ccif/ccwrite
add wave -noupdate /system_tb/DUT/CPU/ccif/cctrans
add wave -noupdate /system_tb/DUT/CPU/ccif/ccsnoopaddr
add wave -noupdate /system_tb/DUT/CPU/ccif/ramWEN
add wave -noupdate /system_tb/DUT/CPU/ccif/ramREN
add wave -noupdate /system_tb/DUT/CPU/ccif/ramstate
add wave -noupdate /system_tb/DUT/CPU/ccif/ramaddr
add wave -noupdate /system_tb/DUT/CPU/ccif/ramstore
add wave -noupdate /system_tb/DUT/CPU/ccif/ramload
add wave -noupdate /system_tb/DUT/CPU/CM/dcif/halt
add wave -noupdate /system_tb/DUT/CPU/CM/dcif/ihit
add wave -noupdate /system_tb/DUT/CPU/CM/dcif/imemREN
add wave -noupdate /system_tb/DUT/CPU/CM/dcif/imemload
add wave -noupdate /system_tb/DUT/CPU/CM/dcif/imemaddr
add wave -noupdate /system_tb/DUT/CPU/CM/dcif/dhit
add wave -noupdate /system_tb/DUT/CPU/CM/dcif/datomic
add wave -noupdate /system_tb/DUT/CPU/CM/dcif/dmemREN
add wave -noupdate /system_tb/DUT/CPU/CM/dcif/dmemWEN
add wave -noupdate /system_tb/DUT/CPU/CM/dcif/flushed
add wave -noupdate /system_tb/DUT/CPU/CM/dcif/dmemload
add wave -noupdate /system_tb/DUT/CPU/CM/dcif/dmemstore
add wave -noupdate /system_tb/DUT/CPU/CM/dcif/dmemaddr
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/JALen
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/RegWr
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ALUSrc
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/dWEN
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/MemtoReg
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/halt
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/beq
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/zero
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/dREN
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/iREN
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/PCSrc
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ExtOp
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/RegDst
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ALUOP
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/imemload
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/rs
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/rd
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/rt
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/imm
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/shamt
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/dhit
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/ihit
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/dmemREN
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/dmemWEN
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/dWEN
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/dREN
add wave -noupdate /system_tb/DUT/CPU/DP/pcif/PCen
add wave -noupdate /system_tb/DUT/CPU/DP/pcif/pc
add wave -noupdate /system_tb/DUT/CPU/DP/pcif/npc
add wave -noupdate /system_tb/DUT/CPU/DP/pcif/cpc
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/WEN
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/wsel
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rsel1
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rsel2
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/wdat
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rdat1
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rdat2
add wave -noupdate /system_tb/DUT/CPU/DP/aluinf/ZERO
add wave -noupdate /system_tb/DUT/CPU/DP/aluinf/OVF
add wave -noupdate /system_tb/DUT/CPU/DP/aluinf/NEG
add wave -noupdate /system_tb/DUT/CPU/DP/aluinf/PORTA
add wave -noupdate /system_tb/DUT/CPU/DP/aluinf/PORTB
add wave -noupdate /system_tb/DUT/CPU/DP/aluinf/OUTPORT
add wave -noupdate /system_tb/DUT/CPU/DP/aluinf/ALUOP
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {1 us}
